### ISSUE TITLE
Stupid Question

### ISSUE THREAD

**Issue by BungaRazvan** [modkhi/yt-playlist#1]
Hey!! Great script, really useful  I was wondering if I can fork this repository for the purpose of adding a UI and a few new features do you mind??

PS: I'm opening an issue because I don't think Github has a way to directly send a message and I don't know how to contact you otherwise.

**Comment by modkhi** [comment]
Hi! Sorry I didn't leave any contact info, I never expected anyone to take interest in my little script. Feel free to fork it and do whatever, and I'd love to see what you decide to do with it! :)
